# Generated by Django 5.2.3 on 2025-06-23 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(help_text='予約日時を選択してください。', verbose_name='予約日時')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='人数')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
            },
        ),
    ]
