# Generated by Django 5.2.3 on 2025-07-22 01:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('name_kana', models.CharField(blank=True, max_length=100, verbose_name='カナ')),
                ('age', models.IntegerField(blank=True, help_text='登録できるのは20歳以上に限ります。', validators=[django.core.validators.MinValueValidator(20)], verbose_name='年齢')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='数字のみ10〜15桁で入力してください', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'そのメールアドレスはすでに登録されています。'}, max_length=63, null=True, unique=True, verbose_name='メールアドレス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客一覧',
                'ordering': ['created_at'],
            },
        ),
    ]
