# Generated by Django 5.2.3 on 2025-06-22 13:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_kana', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, help_text='You must be between the ages of 18 and 60 to register. High school students are not allowed to register.', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)])),
                ('phone', models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')])),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=63, unique=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '顧客verbose_name',
                'verbose_name_plural': '顧客一覧verbose_name_plural',
            },
        ),
    ]
