# Generated by Django 5.2.3 on 2025-06-22 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, help_text='登録できるのは20歳以上に限ります。', validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'そのメールアドレスはすでに登録されています。'}, max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='数字のみ10〜15桁で入力してください', regex='^[0-9]+$')]),
        ),
    ]
