# Generated by Django 5.2.3 on 2025-07-15 14:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_at'], 'verbose_name': '顧客', 'verbose_name_plural': '顧客一覧'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, help_text='登録できるのは20歳以上に限ります。', validators=[django.core.validators.MinValueValidator(20)], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'そのメールアドレスはすでに登録されています。'}, max_length=63, null=True, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='カナ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='数字のみ10〜15桁で入力してください', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
