# Generated by Django 5.2.3 on 2025-07-25 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kanji', models.CharField(help_text='姓と名を続けて入力してください（例：山田太郎）', max_length=20, verbose_name='氏名')),
                ('name_kana', models.CharField(blank=True, help_text='全角カタカナで入力してください（例：ヤマダタロウ）', max_length=20, verbose_name='氏名カナ')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('line_name', models.CharField(blank=True, max_length=20, verbose_name='LINE名')),
                ('branch', models.IntegerField(choices=[(1, '福岡薬院'), (2, '仙台広瀬'), (3, '北九州小倉'), (4, '鹿児島中央'), (5, '仙台東口'), (6, '鹿児島天文館'), (7, '東京新宿')], verbose_name='登録店舗')),
                ('idcard', models.CharField(blank=True, choices=[('unknown', '不明'), ('none', '公的証なし'), ('license', '運転免許証'), ('passport', 'パスポート'), ('my_number', 'マイナカード'), ('permanent_card', '永住カード'), ('resident_card', '住民票'), ('residence_card', '在留カード'), ('student_id', '学生証'), ('employee_id', '社員証'), ('other', 'その他')], default='unknown', help_text='「その他」を選ばれた場合は、備考欄に身分証の「種類」または「名称」をご入力ください。', max_length=20, verbose_name='身分証')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
            ],
            options={
                'verbose_name': '個人',
                'verbose_name_plural': '個人一覧',
            },
        ),
    ]
