# Generated by Django 5.2.3 on 2025-07-22 11:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='氏名')),
                ('full_name_kana', models.CharField(blank=True, max_length=20, null=True, verbose_name='氏名カナ')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('phone', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='電話番号は『09012345678』の形式で、最大11桁まで入力してください。', regex='^[0-9]+$')], verbose_name='PHONE')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('line_name', models.CharField(blank=True, max_length=20, verbose_name='LINE')),
                ('branch', models.CharField(blank=True, choices=[(1, '福岡薬院'), (2, '仙台広瀬'), (3, '北九州小倉'), (4, '鹿児島中央'), (5, '仙台東口'), (6, '鹿児島天文館'), (7, '東京新宿')], max_length=20, verbose_name='登録店舗')),
                ('idcard', models.CharField(blank=True, choices=[('unknown', '不明'), ('none', '公的証なし'), ('license', '運転免許証'), ('passport', 'パスポート'), ('my_number', 'マイナカード'), ('permanent_card', '永住カード'), ('resident_card', '住民票'), ('residence_card', '在留カード'), ('student_id', '学生証'), ('employee_id', '社員証'), ('other', 'その他')], default='unknown', help_text='「その他」を選んだ場合は備考欄に詳細を入力してください。', max_length=20, verbose_name='身分証')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
