# Generated by Django 5.2.3 on 2025-07-16 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_brand_delete_trade_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '身分証',
                'verbose_name_plural': '身分証',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='氏名')),
                ('full_name_kana', models.CharField(blank=True, max_length=20, null=True, verbose_name='氏名カナ')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 11 digits allowed.", regex='^[0-9]+$')], verbose_name='TEL')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('line_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='LINE')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.branch', verbose_name='登録店舗')),
                ('idcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persons.idcard', verbose_name='身分証')),
            ],
            options={
                'verbose_name': '個人',
                'verbose_name_plural': '個人',
            },
        ),
    ]
