# Generated by Django 5.2.3 on 2025-07-17 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='name',
            field=models.CharField(max_length=20, verbose_name='身分証'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 11 digits allowed.", regex='^[0-9]+$')], verbose_name='PHONE'),
        ),
    ]
