# Generated by Django 5.2.3 on 2025-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.IntegerField(blank=True, choices=[(1, '福岡薬院'), (2, '仙台広瀬'), (3, '北九州小倉'), (4, '鹿児島中央'), (5, '仙台東口'), (6, '鹿児島天文館'), (7, '東京新宿')], max_length=20, null=True, verbose_name='登録店舗'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name_kana',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='氏名カナ'),
            preserve_default=False,
        ),
    ]
