# Generated by Django 5.2.3 on 2025-07-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_kana',
            field=models.CharField(blank=True, help_text='全角カタカナで入力してください（例：ヤマダタロウ）', max_length=20, verbose_name='フリガナ'),
        ),
    ]
