# Generated by Django 5.2.3 on 2025-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_branch_alter_person_full_name_kana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '個人', 'verbose_name_plural': '個人一覧'},
        ),
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.IntegerField(choices=[(1, '福岡薬院'), (2, '仙台広瀬'), (3, '北九州小倉'), (4, '鹿児島中央'), (5, '仙台東口'), (6, '鹿児島天文館'), (7, '東京新宿')], default=1, max_length=20, verbose_name='登録店舗'),
            preserve_default=False,
        ),
    ]
