# Generated by Django 5.2.3 on 2025-07-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_idcard'),
        ('persons', '0002_alter_idcard_name_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='idcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.idcard', verbose_name='身分証'),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '個人', 'verbose_name_plural': '個人一覧'},
        ),
        migrations.DeleteModel(
            name='Idcard',
        ),
    ]
