# Generated by Django 5.2.3 on 2025-07-21 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_person_idcard_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='idcard',
            field=models.CharField(blank=True, choices=[('unknown', '不明'), ('none', '有効な身分証なし'), ('license', '運転免許証'), ('passport', 'パスポート'), ('my_number', 'マイナカード'), ('resident_card', '住民票'), ('permanent_card', '永住カード'), ('residence_card', '在留カード'), ('student_id', '学生証'), ('employee_id', '社員証'), ('other', 'その他')], default='unknown', help_text='「その他」を選んだ場合は備考欄に詳細を入力してください。', max_length=20, verbose_name='身分証'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='noemail@example.com', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='電話番号は『09012345678』の形式で、最大11桁まで入力してください。', regex='^[0-9]+$')], verbose_name='PHONE'),
            preserve_default=False,
        ),
    ]
