# Generated by Django 5.2.3 on 2025-07-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_person_email_alter_person_idcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='idcard',
            field=models.CharField(blank=True, choices=[('unknown', '不明'), ('none', '有効な身分証なし'), ('license', '運転免許証'), ('passport', 'パスポート'), ('my_number', 'マイナカード'), ('permanent_card', '永住カード'), ('resident_card', '住民票'), ('residence_card', '在留カード'), ('student_id', '学生証'), ('employee_id', '社員証'), ('other', 'その他')], default='unknown', help_text='「その他」を選んだ場合は備考欄に詳細を入力してください。', max_length=20, verbose_name='身分証'),
        ),
    ]
