# Generated by Django 5.2.3 on 2025-07-22 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('alice', 'アリス'), ('rose', 'ローズ'), ('adele', 'アデル'), ('labo', 'ラボ'), ('mychannel', 'Myチャネ'), ('unknown', '不明'), ('outreach', '掘起')], max_length=20, verbose_name='屋号')),
                ('method', models.CharField(blank=True, choices=[('line', 'LINE'), ('phone', '電話'), ('email', 'メール'), ('friend', '友人紹介'), ('other', '他社紹介'), ('reapply', '再応募')], max_length=20, verbose_name='応募方法')),
                ('content', models.TextField(blank=True, null=True, verbose_name='問い合わせ内容')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='受付日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_inquiries', to='persons.person', verbose_name='個人')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='面接日時')),
                ('status', models.CharField(choices=[('scheduled', '予定'), ('completed', '完了'), ('canceled', 'キャンセル')], max_length=20, verbose_name='面接ステータス')),
                ('result_status', models.CharField(blank=True, choices=[('pass', '合格'), ('fail', '不合格'), ('pending', '保留'), ('no_show', '無断欠席')], max_length=20, null=True, verbose_name='結果')),
                ('result_memo', models.TextField(blank=True, null=True, verbose_name='結果メモ')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='結果入力日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='inquiries.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, verbose_name='受付メモ')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='受付日時')),
                ('status', models.CharField(choices=[('new', '未対応'), ('handling', '対応中'), ('pending', '保留'), ('rejected', '不採用'), ('declined', '辞退'), ('rescheduled', '日程変更'), ('under_consideration', '検討中'), ('lost_contact', '連絡途絶'), ('ignored', '対応不要'), ('decided', '面接決定'), ('completed', '対応完了'), ('canceled', 'キャンセル')], default='new', max_length=20, verbose_name='対応状況')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='inquiries.inquiry', verbose_name='問い合わせ')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
        ),
    ]
