# Generated by Django 5.2.3 on 2025-07-17 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_idcard_name_alter_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('category', models.CharField(choices=[('contact', '連絡手段'), ('referral', '紹介'), ('media', '媒体'), ('other', 'その他')], default='contact', max_length=30, verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '応募経路',
                'verbose_name_plural': '応募経路',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='問い合わせ内容')),
                ('status', models.CharField(choices=[('new', '未対応'), ('handling', '対応中'), ('completed', '完了'), ('canceled', 'キャンセル'), ('lost_contact', '連絡途絶')], default='new', max_length=20, verbose_name='対応状況')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='受付日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='persons.person', verbose_name='個人')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inquiries.inquirymethod', verbose_name='応募方法')),
            ],
            options={
                'verbose_name': '問い合わせ',
                'verbose_name_plural': '問い合わせ',
            },
        ),
    ]
