# Generated by Django 5.2.3 on 2025-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': '問い合わせ', 'verbose_name_plural': '問い合わせ一覧'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='brand',
            field=models.CharField(choices=[('alice', 'アリス'), ('rose', 'ローズ'), ('adele', 'アデル'), ('labo', 'ラボ'), ('mychannel', 'Myチャネ'), ('unknown', '不明'), ('outreach', '掘起')], max_length=20, verbose_name='屋号'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='method',
            field=models.CharField(choices=[('line', 'LINE'), ('phone', '電話'), ('email', 'メール'), ('friend', '友人紹介'), ('other', '他社紹介'), ('reapply', '再応募')], max_length=20, verbose_name='応募方法'),
        ),
    ]
