# Generated by Django 5.2.3 on 2025-07-31 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_previous_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-received_at'], 'verbose_name': '問い合わせ', 'verbose_name_plural': '問い合わせ一覧'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='内容メモ'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', '未対応'), ('handling', '対応中'), ('pending', '保留'), ('rejected', '不採用'), ('declined', '辞退'), ('rescheduled', '日程変更'), ('under_consideration', '検討中'), ('lost_contact', '連絡途絶'), ('ignored', '対応不要'), ('decided', '面接決定'), ('completed', '対応完了'), ('canceled', 'キャンセル')], default='new', max_length=20, verbose_name='対応状況'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='previous_inquiry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.inquiry'),
        ),
    ]
