# Generated by Django 5.2.3 on 2025-07-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_reception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ['-received_at'], 'verbose_name': '受付', 'verbose_name_plural': '受付一覧'},
        ),
        migrations.AlterModelTable(
            name='reception',
            table=None,
        ),
    ]
