# Generated by Django 5.2.3 on 2025-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiry_options_inquiry_remarks_inquiry_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(blank=True, choices=[('interview_only', '面接のみ'), ('trial_wish', '体験希望'), ('discuss', '話し次第'), ('inquiry', '問い合わせ'), ('suggestion', '打診'), ('interview_suggestion', '面接打診'), ('phone_interview', '電話面接')], max_length=20, null=True, verbose_name='問合区分'),
        ),
    ]
