# Generated by Django 5.2.3 on 2025-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_reception_options_alter_reception_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('new', '未対応'), ('handling', '対応中'), ('lost_contact', '連絡途絶'), ('ignored', '対応不要'), ('completed', '対応完了'), ('canceled', 'キャンセル')], default='new', max_length=20, verbose_name='対応状況'),
        ),
    ]
