# Generated by Django 5.2.3 on 2025-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_remove_inquiry_status_alter_reception_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': '問い合わせ', 'verbose_name_plural': '問い合わせ一覧'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
