# Generated by Django 5.2.3 on 2025-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_inquiry_options_inquiry_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='memo',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='memo',
        ),
    ]
