# Generated by Django 5.2.3 on 2025-07-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_rename_memo_reception_remarks_remove_inquiry_memo'),
        ('masters', '0004_idcard'),
        ('persons', '0003_alter_person_idcard_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='brand_inquiries', to='masters.brand', verbose_name='屋号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_inquiries', to='persons.person', verbose_name='個人'),
        ),
    ]
