# Generated by Django 5.2.3 on 2025-07-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_inquiry_brand_alter_inquiry_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='created_at',
            new_name='received_at',
        ),
    ]
