# Generated by Django 5.2.3 on 2025-07-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_rename_created_at_inquiry_received_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='inquiries.inquiry', verbose_name='問い合わせ'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='受付日時'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='受付メモ'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('new', '未対応'), ('handling', '対応中'), ('pending', '保留'), ('rejected', '不採用'), ('declined', '辞退'), ('rescheduled', '日程変更'), ('under_consideration', '検討中'), ('lost_contact', '連絡途絶'), ('ignored', '対応不要'), ('decided', '面接決定'), ('completed', '対応完了'), ('canceled', 'キャンセル')], default='new', max_length=20, verbose_name='対応状況'),
        ),
    ]
