# Generated by Django 5.2.3 on 2025-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=20, verbose_name='支店名'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(max_length=20, verbose_name='業種名'),
        ),
    ]
