# Generated by Django 5.2.3 on 2025-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_branch_name_alter_trade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='屋号')),
            ],
            options={
                'verbose_name': '屋号',
                'verbose_name_plural': '屋号',
            },
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '支店', 'verbose_name_plural': '支店'},
        ),
    ]
