# Generated by Django 5.2.3 on 2025-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_brand_delete_trade_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='身分証')),
            ],
            options={
                'verbose_name': '身分証',
                'verbose_name_plural': '身分証',
            },
        ),
    ]
