# Generated by Django 5.2.3 on 2025-07-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_idcard'),
        ('persons', '0004_alter_person_email_alter_person_idcard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idcard',
        ),
    ]
