# Generated by Django 5.2.3 on 2025-07-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0002_alter_inquiry_options_alter_inquiry_brand_and_more'),
        ('persons', '0003_alter_person_options_alter_person_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiry')),
                ('interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.interview')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('reception', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.reception')),
            ],
        ),
    ]
