# Generated by Django 5.2.3 on 2025-07-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiry')),
                ('interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.interview')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('reception', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.reception')),
            ],
        ),
    ]
