# Generated by Django 5.2.3 on 2025-07-26 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        ('inquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'エントリ', 'verbose_name_plural': 'エントリ'},
        ),
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('new', '新規'), ('pending', '保留'), ('completed', '完了')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.interview'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reception',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='inquiries.reception'),
            preserve_default=False,
        ),
    ]
