# Generated by Django 5.2.3 on 2025-06-22 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ボトルの銘柄名を入力してください', max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('opened_at', models.DateField(blank=True, help_text='ボトルのキープ日を入力してください', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='customers.customer')),
            ],
        ),
    ]
